feat: add custom auth token sign in
robingenz/capacitor-firebase-authentication pull request #100
Opened 2021-11-12 12:12 UTC by F7Fabian

Hi,

this PR adds the `signInWithCustomToken` feature.
https://firebase.google.com/docs/auth/android/custom-auth

The authentication only works on the native layer for android and ios because no credential object is returned from the firebase sdk.
The custom token must be known in the web layer anyway and therefore the web layer can be authenticated directly using the js-sdk.

Thanks for this awesome plugin!

2021-11-12 19:51 UTC, robingenz requested changes
Thank you for your contribution!
Looks very good so far.
Please contact me if you have any questions. I hope you agree with my suggestions.

2021-11-12 19:51 UTC, robingenz commented on src/definitions.ts
> +  signInWithCustomToken(token: string): Promise<SignInResult>;
```suggestion
  signInWithCustomToken(options: SignInWithCustomTokenOptions): Promise<SignInResult>;
```

```js
export interface SignInWithCustomTokenOptions {
    /**
     * The custom token to sign in with.
     */
    token: string;
}
```

2021-11-12 19:51 UTC, robingenz commented on android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthentication.java
> +        "signInWithCustomToken only works on the native layer. Use the js-sdk directly for web layer custom auth https://firebase.google.com/docs/auth/web/custom-auth.";
```suggestion
        "signInWithCustomToken cannot be used in combination with skipNativeAuth.";
```

I suggest that we keep the error message simple here and add a helpful description for it in the `definitions.ts` file.

2021-11-12 19:51 UTC, robingenz commented on ios/Plugin/FirebaseAuthentication.swift
> +    public let errorCustomTokenUnimplemented = "signInWithCustomToken only works on the native layer. Use the js-sdk directly for the web layer https://firebase.google.com/docs/auth/web/custom-auth."
```suggestion
    public let errorCustomTokenSkipNativeAuth = "signInWithCustomToken cannot be used in combination with skipNativeAuth.";
```

I suggest that we keep the error message simple here and add a helpful description for it in the `definitions.ts` file.

2021-11-12 19:51 UTC, robingenz commented on android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthentication.java
> +        }
```suggestion
        String token = call.getString("token", "");
```

I would keep the code as simple as possible at this point. 
Extensive error handling will be added soon.

2021-11-12 19:51 UTC, robingenz commented on ios/Plugin/FirebaseAuthentication.swift
> +        }
```suggestion
        let token = call.getString("token", "")
```


I would keep the code as simple as possible at this point. 
Extensive error handling will be added soon.

2021-11-12 19:51 UTC, robingenz commented on android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthentication.java
> +            call.unimplemented(ERROR_CUSTOM_TOKEN_UNIMPLEMENTED);
```suggestion
            call.reject(ERROR_CUSTOM_TOKEN_SKIP_NATIVE_AUTH);
```

2021-11-12 19:51 UTC, robingenz commented on android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/auth/FirebaseAuthentication.java
> +    public static final String ERROR_CUSTOM_TOKEN_UNIMPLEMENTED =
```suggestion
    public static final String ERROR_CUSTOM_TOKEN_SKIP_NATIVE_AUTH =
```

2021-11-12 19:51 UTC, robingenz commented on ios/Plugin/FirebaseAuthentication.swift
> +            call.unimplemented(self.errorCustomTokenUnimplemented)
```suggestion
            call.reject(self.errorCustomTokenSkipNativeAuth)
```

2021-11-12 19:51 UTC, robingenz commented on src/definitions.ts
> +   */
```suggestion
  /**
   * Starts the Custom Token sign-in flow.
   * 
   * This method cannot be used in combination with `skipNativeAuth` on Android and iOS.
   * In this case you have to use the `signInWithCustomToken` interface of the Firebase JS SDK directly.
   */
```

2021-11-13 10:17 UTC, robingenz commented
@F7Fabian Thank you for the changes. Please run `npm run docgen` again.

2021-11-13 10:19 UTC, F7Fabian commented
@robingenz hi, i am implemented your changes at the moment. 
do you want me to squash all into one commit (you would loose the co author status of your changes i think)?

2021-11-13 10:26 UTC, robingenz commented
@F7Fabian No problem. If you want, you can squash. Just keep pushing your changes to this branch.
The PR will be squashed into the main branch in the end anyway.

2021-11-13 11:48 UTC, robingenz approved these changes

2021-11-13 11:49 UTC, robingenz commented
Some documentation is still missing regarding the setup, but I'll add that in another PR.

@F7Fabian Thank you very much for your contribution! I plan to publish an update this weekend.

2021-11-13 21:55 UTC, merged